require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
